"""Typed deterministic cluster reconciliation for Phase 4 v2."""

from .engine import (
    RESULT_REVISION,
    AreaAggregate,
    AtomSource,
    ComparisonDecision,
    Contradiction,
    FullPromotion,
    PackageResultReference,
    PairDecision,
    ReconciliationResult,
    RepairRequirement,
    RootResultReference,
    SemanticAtom,
    reconcile,
)
from .final_ir import (
    FinalIRSurfaceDerivation,
    derive_authenticated_final_ir_package_surface,
)
from .model import (
    AreaSurface,
    CanonicalValue,
    ClaimPolarity,
    ClosureStatus,
    ComparisonArea,
    DispositionKind,
    DispositionStatus,
    LeafProvenance,
    LedgerDisposition,
    NormalizedClaim,
    PackageSurface,
    ReconciliationError,
    ReconciliationInput,
    RootProvenance,
    dumps_input,
    loads_input,
)
from .render import render_json, render_markdown, verify_render_agreement
from .schema import (
    COMPARISON_AREAS,
    INPUT_SCHEMA_CANONICAL_BYTES,
    INPUT_SCHEMA_REVISION,
    INPUT_SCHEMA_SHA256,
    schema_document,
)

__all__ = [
    "COMPARISON_AREAS",
    "INPUT_SCHEMA_CANONICAL_BYTES",
    "INPUT_SCHEMA_REVISION",
    "INPUT_SCHEMA_SHA256",
    "RESULT_REVISION",
    "AreaAggregate",
    "AreaSurface",
    "AtomSource",
    "CanonicalValue",
    "ClaimPolarity",
    "ClosureStatus",
    "ComparisonArea",
    "ComparisonDecision",
    "Contradiction",
    "DispositionKind",
    "DispositionStatus",
    "FullPromotion",
    "FinalIRSurfaceDerivation",
    "LeafProvenance",
    "LedgerDisposition",
    "NormalizedClaim",
    "PackageResultReference",
    "PackageSurface",
    "PairDecision",
    "ReconciliationError",
    "ReconciliationInput",
    "ReconciliationResult",
    "RepairRequirement",
    "RootProvenance",
    "RootResultReference",
    "SemanticAtom",
    "dumps_input",
    "derive_authenticated_final_ir_package_surface",
    "loads_input",
    "reconcile",
    "render_json",
    "render_markdown",
    "schema_document",
    "verify_render_agreement",
]
